version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://sajan:sajan@cluster0.cug7zzx.mongodb.net/TODO-List
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
